#!/bin/bash

declare -A XILINX_MAP
XILINX_INSTALL_DIR=/opt/xilinx
NEW_HOME=~

[[ -f ~/.config/nacs-lab/planahead_env.sh ]] && \
    . ~/.config/nacs-lab/planahead_env.sh

mkdir -p "${NEW_HOME}" "${XILINX_INSTALL_DIR}" "/tmp/xilinx"

ln -sfT "${XILINX_INSTALL_DIR}" /tmp/xilinx/planahead
ln -sfT "${NEW_HOME}" /tmp/xilinx/home

for name in "${!XILINX_MAP[@]}"; do
    mkdir -p "${XILINX_MAP["${name}"]}"
    mkdir -p "$(dirname "/tmp/xilinx/${name}")"
    ln -sfT "${XILINX_MAP["${name}"]}" "/tmp/xilinx/${name}"
done

export XAUTHORITY=${XAUTHORITY:-~/.Xauthority}
export HOME="/tmp/xilinx/home"

XILINX_HOME="/tmp/xilinx/planahead/14.7"

# export XILINXD_LICENSE_FILE=PORTNUMBER@HOSTNAME
export XILINXD_LICENSE_FILE="${XILINX_HOME}/ISE_DS/xilinx_ise.lic"

ISE_DS_PATH="${XILINX_HOME}/ISE_DS"

PATH="$PATH:$ISE_DS_PATH/ISE/bin/lin64:$ISE_DS_PATH/EDK/bin/lin64"
PATH="$PATH:$ISE_DS_PATH/common/bin/lin64"
PATH="$PATH:$ISE_DS_PATH/ISE/sysgen/bin/lin64:$ISE_DS_PATH/ISE/sysgen/util"
export PATH="$PATH:$ISE_DS_PATH/PlanAhead/bin"
export XILINX="$ISE_DS_PATH/ISE/"
export XILINX_DSP="$ISE_DS_PATH/ISE/"
export XILINX_PLANAHEAD="$ISE_DS_PATH/PlanAhead/"
. "$ISE_DS_PATH/settings64.sh" &> /dev/null

cd ~
LANG=C
QT_PLUGIN_PATH=
QT_IM_MODULE=
exec "$ISE_DS_PATH/PlanAhead/bin/planAhead" "$@"
