#!/bin/bash

export XAUTHORITY=${XAUTHORITY:-~/.Xauthority}
export HOME="/tmp/xilinx/home"

XILINX_HOME="/tmp/xilinx/xilinx/14.7"

# export XILINXD_LICENSE_FILE=PORTNUMBER@HOSTNAME
export XILINXD_LICENSE_FILE="${XILINX_HOME}/ISE_DS/xilinx_ise.lic"

ISE_DS_PATH="${XILINX_HOME}/ISE_DS"

PATH="$PATH:$ISE_DS_PATH/ISE/bin/lin64:$ISE_DS_PATH/EDK/bin/lin64"
PATH="$PATH:$ISE_DS_PATH/common/bin/lin64"
PATH="$PATH:$ISE_DS_PATH/ISE/sysgen/bin/lin64:$ISE_DS_PATH/ISE/sysgen/util"
export PATH="$PATH:$ISE_DS_PATH/PlanAhead/bin"
export XILINX="$ISE_DS_PATH/ISE/"
export XILINX_DSP="$ISE_DS_PATH/ISE/"
export XILINX_PLANAHEAD="$ISE_DS_PATH/PlanAhead/"
. "$ISE_DS_PATH/settings64.sh" &> /dev/null

cd ~
LANG=C
QT_PLUGIN_PATH=
QT_IM_MODULE=
exec "$ISE_DS_PATH/PlanAhead/bin/planAhead" "$@"
