#!/bin/bash

declare -A XILINX_MAP
XILINX_INSTALL_DIR=/opt/xilinx
NEW_HOME=~

[[ -f ~/.config/nacs-lab/xilinx_env.sh ]] && \
    . ~/.config/nacs-lab/xilinx_env.sh

mkdir -p "${NEW_HOME}" "${XILINX_INSTALL_DIR}" "/tmp/xilinx"

ln -vsfT "${XILINX_INSTALL_DIR}" /tmp/xilinx/xilinx
ln -vsfT "${NEW_HOME}" /tmp/xilinx/home

for name in "${!XILINX_MAP[@]}"; do
    mkdir -p "${XILINX_MAP["${name}"]}"
    mkdir -p "$(dirname "/tmp/xilinx/${name}")"
    ln -vsfT "${XILINX_MAP["${name}"]}" "/tmp/xilinx/${name}"
done
