#!/bin/bash

# Script to fix Xilinx SDK's broken installation on non-ancient Linux

LIB_XILINX_DIR=$(dirname "${BASH_SOURCE}")

ise_ds_dir=$1

die() {
    printf "$@" >&2
    exit 1
}

[[ -z "$ise_ds_dir" ]] && {
    [[ -f ~/.config/nacs-lab/xilinx_env.sh ]] && \
        . ~/.config/nacs-lab/xilinx_env.sh
    ise_ds_dir="${XILINX_INSTALL_DIR}/14.7/ISE_DS"
}

[[ -d "$ise_ds_dir" ]] || die "Directory '%s' does not exist" "$ise_ds_dir"

chmod -R u+w "$ise_ds_dir"/{common,EDK}

# planAhead uses gmake
ln -vsfT /usr/bin/make "$ise_ds_dir/common/bin/lin/gmake"
ln -vsfT /usr/bin/make "$ise_ds_dir/common/bin/lin64/gmake"

# TODO? find library first
ln -vsfT /usr/lib/libstdc++.so "$ise_ds_dir/common/lib/lin/libstdc++.so"
ln -vsfT /usr/lib/libstdc++.so "$ise_ds_dir/common/lib/lin/libstdc++.so.6"
ln -vsfT /usr/lib/libstdc++.so "$ise_ds_dir/common/lib/lin/libstdc++.so.6.0.8"
ln -vsfT /usr/lib/libXm.so "$ise_ds_dir/common/lib/lin/libXm.so.3"

ln -vsfT /usr/lib/libstdc++.so "$ise_ds_dir/common/lib/lin64/libstdc++.so"
ln -vsfT /usr/lib/libstdc++.so "$ise_ds_dir/common/lib/lin64/libstdc++.so.6"
ln -vsfT /usr/lib/libstdc++.so "$ise_ds_dir/common/lib/lin64/libstdc++.so.6.0.8"
ln -vsfT /usr/lib/libXm.so "$ise_ds_dir/common/lib/lin64/libXm.so.3"

ln -vsf "${LIB_XILINX_DIR}/xsdk-plugin/" \
    "$ise_ds_dir/EDK/eclipse/lin64/eclipse/dropins/"

chmod -R og-rwx "$ise_ds_dir"
chmod -R u-w "$ise_ds_dir/"*
