#!/bin/bash

XILINX_INSTALL_DIR=/opt/xilinx
NEW_HOME=~

[[ -f ~/.config/nacs-lab/xilinx_env.sh ]] && \
    . ~/.config/nacs-lab/xilinx_env.sh

mkdir -p "${NEW_HOME}" "${XILINX_INSTALL_DIR}" "/tmp/xilinx"

ln -vsfT "${XILINX_INSTALL_DIR}" /tmp/xilinx/xilinx
ln -vsfT "${NEW_HOME}" /tmp/xilinx/home
