#!/bin/bash

output=$(realpath "$1")

run_planAhead() {
    planAhead -mode batch -source /dev/stdin <<EOF
open_project /tmp/planahead/hw_src/project_1.ppr
open_impl_design impl_1
write_bitstream $output
EOF
}
