#!/bin/bash

PLANAHEAD=${PLANAHEAD:-planAhead}
declare -A PLANAHEAD_MAP
PLANAHEAD_INSTALL_DIR=/opt/planahead
NEW_HOME=~
curdir=$(realpath $(dirname "${BASH_SOURCE}"))

[[ -f ~/.config/nacs-lab/planahead_env.sh ]] && \
    . ~/.config/nacs-lab/planahead_env.sh

mkdir -p "${PLANAHEAD_INSTALL_DIR}" "/tmp/planahead/planahead" \
    "${NEW_HOME}" "/tmp/planahead/home"

bind_args=(-m "${PLANAHEAD_INSTALL_DIR}" "/tmp/planahead/planahead"
    -m "${NEW_HOME}" "/tmp/planahead/home")

for name in "${!PLANAHEAD_MAP[@]}"; do
    bind_args+=(-m "${PLANAHEAD_MAP["${name}"]}" "/tmp/planahead/${name}")
    mkdir -p "${PLANAHEAD_MAP["${name}"]}" "/tmp/planahead/${name}"
done

exec bind_dirs "${bind_args[@]}" "${curdir}/run_in_xephyr" \
    "${curdir}/planahead_wrapper" "${PLANAHEAD}" "$@"
